# Page settings
baseurl = "localhost:1313"
title = "JavaFX"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = 'JavaFX'
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Community"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #   url = "http://docs.gluonhq.com/javafx11/#install-javafx"
    #   name = "Getting Started"
    #   weight = 10

    
  # Hero section
  [params.hero]
    title = 'JavaFX 11'
    subtitle = 'OpenJFX is an open source, next generation client application platform for desktop, mobile and embedded systems based on JavaSE.</br> It is a collaborative effort by many individuals and companies with the goal of producing a modern, efficient, and fully featured toolkit for developing rich client applications.</br></br>'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Getting Started"
    description = "This tutorial will help you to write a JavaFX 11 application and run it on mulitple desktop platforms."
    url = "http://docs.gluonhq.com/javafx11/#install-javafx"
    button = "Start"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Download"
    description = "The JavaFX 11 runtime is available as a platform-specifc SDK, as a number of jmods, and as a set of artifacts in maven central."
    url = "https://gluonhq.com/products/javafx/"
    button = "Download"
    icon = "icon-cloud-download"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "OpenJFX is free software, licensed under the GPL with the class path exception, just as OpenJDK."
    url = "https://github.com/javafxports/openjdk-jfx"
    button = "Let's do it!"
    icon = "icon-social-github"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

 # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;I'm excited to see the more folks from the wider Java Community working together with Oracle on JavaFX. This release proves there is a great future for client-side Java development. As an OpenJDK Project , OpenJFX shares much of its principles and infrastructure, leading to a high-quality release that is very well aligned with the upcoming Java 11 release.&rdquo;"
      person = 'Georges Saab <span class="subtext">Vice President, Software Development, Java Platform Group at <a href="https://www.oracle.com/java/" target="_blank">Oracle</a></span>'
      img = "Saab.jpg"
      alt = "Georges Saab"

    [[params.testimonials.item]]
      quote = "&ldquo;For me OpenJFX represents a major milestone in the ongoing effort to make JavaFX the leading technology for mobile, embedded, and desktop applications. Finally Java has an advanced UI toolkit that can evolve independently of JDK development activities backed by a passionate developer community that can directly contribute to its future. All that is needed to use OpenJFX is to add a dependency to your Maven or Gradle build and things just work. The OpenJFX team has done a fantastic job to make using JavaFX as simple as adding any other third party library. If you know how to add Apache Commons libraries to your build then you know how to add JavaFX. I have no doubt that OpenJFX will have a bright future ahead of it. The best is yet to come!&rdquo;"
      person = 'Dirk Lemmermann <span class="subtext">CEO of <a href="https://dlsc.com" target="_blank">DLSC Software & Consulting GmbH</a></span>'
      img = "Lemmermann.jpg"
      alt = "Dirk Lemmermann"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"


  # Work section
  [params.work]
    enable = false
    title = "Commuity"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      #img = "work_1.jpg"
      #alt = "Image2"
      title = "FlexxGantFX"
      subtitle = "Dirk Lemmermann Software & Consulting"

    [[params.work.row]]
      #img = "work_2.jpg"
      #alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      #img = "work_3.jpg"
      #alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      #img = "work_4.jpg"
      #alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      #img = "work_5.jpg"
      #alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      #img = "work_6.jpg"
      #alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

 
  # Services section
  [params.services]
    enable = true
    title = "Community"
    description = "JavaFX features a vibrant and passionate developer community. This enthusiasm can be found in the open source mailing list, the forum discussions. Here just some of the examples of tools and frameworks already supporting JavaFX 11"

    [[params.services.item]]
      title = '<a href="https://dlsc.com/products/flexganttfx/" target="_blank">FlexGanttFX</a>'
      description = 'FlexGanttFX is the most advanced JavaFX-based Gantt charting framework currently available for Java. It uses a very high abstraction level, which allows it to be applied in various and often very different domains such as ERP systems, production planning and scheduling applications, manufacturing execution systems or project portfolio management applications. FlexGanttFX and its predecessor frameworks FlexGantt (for Swing) and DJT have been used and tested by hundreds of professional planning and scheduling applications. The customer list contains companies such as Siemens, Boeing, NASA, JPL, Lockhead Martin, Raytheon, Kuehne + Nagel, SAIC, General Dynamics, ABAS, Bauer, etc…'
      icon = "icon-layers"

    [[params.services.item]]
      title = '<a href="https://gluonhq.com/labs/maps/" target="_blank">Gluon Maps</a>'
      description = "Gluon Maps is built with high performance in mind, but that doesn’t mean functionality is missing. Gluon Maps offers layer overlays, multiple tilesets, and much more."
      icon = "icon-map"

    #[[params.services.item]]
    #  title = "Photo &amp; Video"
    #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in #Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #  icon = "icon-video2"

    #  [[params.services.item]]
    #  title = "CMS &amp; eCommerce"
    #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in #Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
    #  icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = false
    map = true
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
